### ISSUE TITLE
Create `make_child_app()` function

### ISSUE THREAD

**Issue by lauramaxwell** [atorus-research/matte#16]
Add a function that copies the relevant files from a parent app into a new child app. Key features are:
- [x] Copy `app.R`, `R/app_ui.R` and `R/app_server.R` and `manifest.json` from parent app to child app
- [x] Allow `jobs` folder to be copied from `{matte}` template or from parent app
- [ ] Option to include `renv` in the child app
- [x] Allow user to request app-as-package framework (golem or rhino) for child
- [x] Create dependencies in child app to include `@import parent_app_name`

**Comment by MayaGans** [comment]
server.R needs to add a chunk that reads data from data.rds at the beginning of it ?
